### ISSUE TITLE
How to add this library into Android project

### ISSUE THREAD

**Issue by anokmik** [fhur/eaml#1]
Hi!
How can this library be integrated with typical Android project written in Java?
Has it Gradle support?

**Comment by fhur** [comment]
Hi @anokmik. This is currently in the works. As can be seen by the [release notes](https://github.com/fhur/eaml/blob/master/doc/release_notes.md), Gradle integration is planned, it's just not ready yet.
I also plan on providing an Android studio plugin that will make integration into your project a piece of cake.

**Comment by anokmik** [comment]
Great! Thanks! Waiting for this feature very much.
